.\" $Id: pftabled.1,v 1.6 2004/04/24 17:50:08 armin Exp $
.\"
.\" Manpage written by Armin Wolfermann. Public Domain.
.\"
.Dd April 24, 2004
.Dt PFTABLED 1
.Os LOCAL
.Sh NAME
.Nm pftabled
.Nd Remote PF table helper
.Sh SYNOPSIS
.Nm pftabled
.Op Fl a Ar address
.Op Fl d
.Op Fl p Ar port
.Op Fl t Ar timeout
.Op Fl v
.Op Ar table
.Sh DESCRIPTION
The
.Nm
daemon is a small helper to make your
.Xr pf 4
tables reachable from other hosts.
It operates only on the table supplied as an argument.
.Pp
The options are as follows:
.Bl -tag -width Dfxaddress
.It Fl a Ar address
Bind to this address (default: 0.0.0.0).
.It Fl d
Run as daemon in the background.
.It Fl p Ar port
Bind to this port (default: 56789).
.It Fl t Ar timeout
Delete addresses from table after
.Ar timeout
seconds. With this option enabled
.Nm
needs more memory (approx. 16 bytes per active address).
.It Fl v
Log all received commands.
.El
.Pp
Beware that no authentication is performed.
Make sure you pass only authorized packets to
.Nm .
.Pp
The
.Nm
daemon accepts UDP datagrams of the format:
.Bd -literal -offset indent
+--------+--------+--------+--------+
|              Command              |
+--------+--------+--------+--------+
|            IPv4 address           |
+--------+--------+--------+--------+
.Ed
.Pp
With the following commands:
.Bl -tag -width Dfx0x00000001
.It 0x00000001
Add address to table.
.It 0x00000002
Delete address from table.
.It 0x00000003
Flush table.
.El
.Sh SEE ALSO
.Xr pf 4 ,
.Xr pf.conf 5
.Sh VERSION
This manual page describes
.Nm
version 1.02.
.Sh AUTHORS
Armin Wolfermann <armin@wolfermann.org>
