.\" $Id: pftabled.1,v 1.3 2003/10/26 23:52:49 armin Exp $
.\"
.\" Manpage written by Armin Wolfermann. Public Domain.
.\"
.Dd October 22, 2003
.Dt PFTABLED 1
.Os LOCAL
.Sh NAME
.Nm pftabled
.Nd Remote PF table helper
.Sh SYNOPSIS
.Nm pftabled
.Op Fl a Ar address
.Op Fl d
.Op Fl p Ar port
.Op Fl v
.Op Ar table
.Sh DESCRIPTION
The
.Nm
daemon is a small helper to make your
.Xr pf 4
tables reachable from other hosts.
It operates only on the table supplied as an argument.
.Pp
The options are as follows:
.Bl -tag -width Dfxaddress
.It Fl a Ar address
Bind to this address (default: 0.0.0.0).
.It Fl d
Run as daemon in the background.
.It Fl p Ar port
Bind to this port (default: 56789).
.It Fl v
Log all received packets.
.El
.Pp
Beware that no authentication is performed.
Make sure you pass only authorized packets to
.Nm .
.Sh SEE ALSO
.Xr pf 4 ,
.Xr pf.conf 5
.Sh VERSION
This manual page describes
.Nm
version 1.01.
.Sh AUTHORS
Armin Wolfermann <armin@wolfermann.org>
